# Generated by Django 4.1.1 on 2023-09-21 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rfx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CM_Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_id', models.CharField(default=None, max_length=255, null=True)),
                ('Item_Price', models.FloatField(null=True)),
                ('Lead_Time', models.IntegerField(null=True)),
                ('MOQ', models.IntegerField(null=True)),
                ('List', models.CharField(default=' ', max_length=255, null=True)),
                ('tarrif', models.CharField(default=' ', max_length=255, null=True)),
                ('NCNR', models.CharField(default='-', max_length=255, null=True)),
                ('PO_Delivery', models.CharField(max_length=255, null=True)),
                ('suggested_split', models.FloatField(null=True)),
                ('arista_suggested', models.FloatField(null=True)),
                ('manual_split', models.FloatField(null=True)),
                ('std_cost', models.FloatField(null=True)),
                ('CM_comments', models.TextField(default=' ', null=True)),
                ('arista_comments', models.TextField(default='', null=True)),
                ('Supplier_Distributor_name_from_cm', models.TextField(null=True)),
                ('CM_Manufacturer', models.TextField(null=True)),
                ('CM_mpn', models.TextField(null=True)),
                ('split_type', models.CharField(default='Automated', max_length=255, null=True)),
                ('Quote_status', models.CharField(default='Non Quoted', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LockAccessEmailNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arista_Part_Number', models.CharField(default=None, max_length=255, null=True)),
                ('Mfr_Part_Number', models.CharField(max_length=255, null=True)),
                ('Mfr_Name', models.CharField(default=None, max_length=255, null=True)),
                ('Arista_PIC', models.CharField(default=None, max_length=255, null=True)),
                ('team', models.CharField(default=None, max_length=255, null=True)),
                ('cm', models.CharField(default=None, max_length=50, null=True)),
                ('sent_to', models.CharField(default=None, max_length=255, null=True)),
                ('lock_status', models.BooleanField(default=False, null=True)),
                ('status_updated_by', models.TextField(default=None, null=True)),
                ('created_at', models.TextField(default=None, null=True)),
                ('is_email_sent', models.BooleanField(default=False, null=True)),
                ('to', models.TextField(default=None, null=True)),
                ('supplier_email', models.TextField(default=None, null=True)),
                ('sgd_cm_email', models.TextField(default=None, null=True)),
                ('jpe_cm_email', models.TextField(default=None, null=True)),
                ('fgn_cm_email', models.TextField(default=None, null=True)),
                ('hbg_cm_email', models.TextField(default=None, null=True)),
                ('jsj_cm_email', models.TextField(default=None, null=True)),
                ('jmx_cm_email', models.TextField(default=None, null=True)),
                ('rfx_id', models.CharField(default=None, max_length=255, null=True)),
                ('current_url', models.CharField(default=None, max_length=255, null=True)),
                ('logged_in_user_group', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RfqCountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arista_Part_Number', models.CharField(default=None, max_length=255, null=True)),
                ('Mfr_Part_Number', models.CharField(max_length=255, null=True)),
                ('Mfr_Name', models.CharField(default=None, max_length=255, null=True)),
                ('Arista_PIC', models.CharField(default=None, max_length=255, null=True)),
                ('team', models.CharField(default=None, max_length=255, null=True)),
                ('Total_ARISTA_Part_Count', models.CharField(default=None, max_length=255, null=True)),
                ('Total_Part_Count', models.CharField(default=None, max_length=255, null=True)),
                ('RFQ_Initiated', models.CharField(default=None, max_length=255, null=True)),
                ('RFQ_NOT_Initiated', models.CharField(default=None, max_length=255, null=True)),
                ('Quoted', models.CharField(default=None, max_length=255, null=True)),
                ('Non_Quoted', models.CharField(default=None, max_length=255, null=True)),
                ('No_BID', models.CharField(default=None, max_length=255, null=True)),
                ('Locked', models.CharField(default=None, max_length=255, null=True)),
                ('Unlocked', models.CharField(default=None, max_length=255, null=True)),
                ('Award_Set', models.CharField(default=None, max_length=255, null=True)),
                ('commodity', models.CharField(default=None, max_length=255, null=True)),
                ('Not_To_Award', models.CharField(default=None, max_length=255, null=True)),
                ('dtmLastUpdate', models.DateTimeField(auto_now=True)),
                ('LastUpdatedBy', models.CharField(default=None, max_length=255, null=True)),
                ('Chart_Name', models.CharField(default=None, max_length=255, null=True)),
                ('Remarks', models.TextField(default=None, null=True)),
                ('DevRemarks', models.TextField(default=None, null=True)),
                ('Deleted', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='send_fx_queue_logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_create_count', models.IntegerField(null=True)),
                ('Created_count', models.IntegerField(null=True)),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(default='No Error', max_length=1000)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='predefined_filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('data', models.TextField(default='No Error')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Master_history_rfx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('data_dict', models.TextField()),
                ('comment', models.TextField()),
                ('modified_by_email', models.EmailField(max_length=254, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('model_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rfx.rfx')),
                ('modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
