# Generated by Django 4.1.1 on 2023-10-10 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rfx', '0002_cm_quotes_lockaccessemailnotification_rfqcountdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Split_award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_award', models.BooleanField(default=False)),
                ('share_time', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
