# Generated by Django 4.2.3 on 2023-07-19 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='helper_Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255, null=True)),
                ('Quarter', models.CharField(max_length=255, null=True)),
                ('column_mapper', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='logging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('exception', models.CharField(max_length=255, null=True)),
                ('table_name', models.CharField(max_length=255, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quarter', models.CharField(max_length=255, null=True)),
                ('cm', models.CharField(max_length=255, null=True)),
                ('Number', models.CharField(max_length=255, null=True)),
                ('Lifecycle_Phase', models.CharField(max_length=255, null=True)),
                ('commodity', models.CharField(default='Miscellaneous', max_length=255, null=True)),
                ('Rev', models.CharField(max_length=255, null=True)),
                ('Mfr_Name', models.CharField(max_length=255, null=True)),
                ('Mfr_Part_Lifecycle_Phase', models.CharField(max_length=255, null=True)),
                ('Mfr_Part_Number', models.CharField(max_length=255, null=True)),
                ('Qualification_Status', models.CharField(max_length=255, null=True)),
                ('cm_Part_Number', models.CharField(max_length=255, null=True)),
                ('Arista_Part_Number', models.CharField(max_length=255, null=True)),
                ('Cust_consign', models.CharField(max_length=255, null=True)),
                ('Parts_controlled_by', models.CharField(max_length=255, null=True)),
                ('Item_Desc', models.CharField(max_length=255, null=True)),
                ('LT', models.CharField(max_length=255, null=True)),
                ('MOQ', models.CharField(max_length=255, null=True)),
                ('Original_PO_Delivery_sent_by_Mexico', models.CharField(max_length=255, null=True)),
                ('cm_Quantity_Buffer_On_Hand', models.CharField(max_length=255, null=True)),
                ('cm_Quantity_On_Hand_CS_Inv', models.IntegerField(null=True)),
                ('Open_PO_due_in_this_quarter', models.IntegerField(null=True)),
                ('Open_PO_due_in_next_quarter', models.IntegerField(null=True)),
                ('Delivery_Based_Total_OH_sum_OPO_this_quarter', models.IntegerField(null=True)),
                ('PO_Based_Total_OH_sum_OPO', models.IntegerField(null=True)),
                ('CQ_ARIS_FQ_sum_1_SANM_Demand', models.IntegerField(null=True)),
                ('CQ_sum_1_ARIS_FQ_sum_2_SANM_Demand', models.IntegerField(null=True)),
                ('CQ_sum_2_ARIS_FQ_sum_3_SANM_Demand', models.IntegerField(null=True)),
                ('CQ_sum_3_ARIS_FQ_SANM_Demand', models.IntegerField(null=True)),
                ('Delta_OH_and_Open_PO_DD_CQ_sum_CQ_sum_1_Arista', models.IntegerField(null=True)),
                ('ARIS_CQ_SANM_FQ_sum_1_unit_price_USD_Current_std', models.FloatField(max_length=255, null=True)),
                ('CQ_sum_1_ARIS_FQ_sum_2_SANM_unit_price_USD', models.FloatField(max_length=255, null=True)),
                ('Delta_ARIS_CQ_sum_1_SANM_FQ_sum_2_vs_ARIS_CQ_SANM_FQ_sum_1', models.FloatField(max_length=255, null=True)),
                ('Blended_AVG_PO_Receipt_Price', models.FloatField(max_length=255, null=True)),
                ('Ownership', models.CharField(max_length=255, null=True)),
                ('Arista_PIC', models.CharField(max_length=255, null=True)),
                ('Team', models.CharField(max_length=255, null=True)),
                ('rfq_sent_flag_supplier', models.CharField(default='Not Raised', max_length=255, null=True)),
                ('rfq_sent_flag_cm', models.CharField(default='Not Raised', max_length=255, null=True)),
                ('rfq_sent_flag_distributor', models.CharField(default='Not Raised', max_length=255, null=True)),
                ('rfq_sent_distributor', models.CharField(max_length=255, null=True)),
                ('Arista_pic_comment', models.CharField(max_length=255, null=True)),
                ('offcycle', models.BooleanField(default=False, null=True)),
                ('bp_comment', models.TextField(default='', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('refreshed_comment', models.TextField(default='', null=True)),
                ('refreshed_on', models.DateTimeField(null=True)),
                ('refreshed_MRP_date', models.DateTimeField(null=True)),
                ('file_from', models.CharField(default='', max_length=255, null=True)),
                ('sgd_jpe_cost', models.CharField(default='-', max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
