# Generated by Django 4.1.1 on 2023-08-15 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='logger_portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(max_length=255, null=True)),
                ('error', models.TextField(max_length=255, null=True)),
                ('status', models.BooleanField(null=True)),
                ('completed_status', models.BooleanField(default=False, null=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
