# Generated by Django 4.2.3 on 2023-07-20 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='suppliers_detail_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('log', models.TextField(null=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['modified_on'],
            },
        ),
        migrations.CreateModel(
            name='suppliers_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supplier_Name', models.CharField(max_length=255, null=True)),
                ('Team', models.CharField(max_length=255, null=True)),
                ('Distributor', models.CharField(max_length=255, null=True)),
                ('Arista_Commodity_Manager', models.CharField(max_length=255, null=True)),
                ('Commodity', models.CharField(max_length=255, null=True)),
                ('Contact', models.CharField(max_length=255, null=True)),
                ('Position', models.CharField(max_length=255, null=True)),
                ('Direct', models.CharField(max_length=255, null=True)),
                ('Mobile', models.CharField(max_length=255, null=True)),
                ('Email', models.CharField(max_length=255, null=True)),
                ('Comments', models.CharField(max_length=1000, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('User_created', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('logger', models.ManyToManyField(to='Supplier.suppliers_detail_log')),
                ('user_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
