# Generated by Django 4.1.1 on 2023-10-03 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='parts_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpn', models.CharField(max_length=255, null=True)),
                ('commodity', models.CharField(default='Miscellaneous', max_length=255, null=True)),
                ('arista_pic', models.CharField(max_length=255, null=True)),
                ('Ownership', models.CharField(max_length=255, null=True)),
                ('Team', models.CharField(max_length=255, null=True)),
                ('cm', models.CharField(max_length=255, null=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Master_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(null=True)),
                ('notification_read', models.BooleanField(default=False, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(default='/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
